name = "HyperSignal"
uuid = "0aa5b41a-51a1-41e7-8512-17ccb31a7c30"
version = "0.3.0"
authors = ["AIR Centre <joao.goncalves@aircentre.org>"]

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[weakdeps]
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
HyperSignalMakieExt = "Makie"
HyperSignalMapLibreExt = "GeoInterface"

[compat]
GeoInterface = "1"
HTTP = "1, 2"
JSON = "0.21, 1"
Makie = "0.20, 0.21, 0.22, 0.23, 0.24"
julia = "1.10"
